### ISSUE TITLE
Location issues

### ISSUE THREAD

**Issue by miquelvila** [tripleblindmarket/covid-safe-paths#264] opened 2020-03-28 23:06 UTC
I have been using the app for 5 days now, in Spain and in Andorra. I live in the #580 green circle, which is were I have been most of the time. Nevertheless, the app registered that I was 106 times in the #106 green circle, and I absolutely wasn't (maybe I drove my car in front of there, but I could not be registered 106 times there at all...). The main issue is that the distance between the two points is 120 meters (400ft)!

![Image from iOS (1)](https://user-images.githubusercontent.com/62817750/77835844-2a0ce800-7151-11ea-91c3-c7ecd33679b2.png)

Then there is this problem as well, this was a U-turn I did with my car in the road. I assume when the app detects a sudden change in direction it increases the registration frequency maybe

![Image from iOS](https://user-images.githubusercontent.com/62817750/77835847-309b5f80-7151-11ea-978c-fa08438aff77.png)

**Comment by E3V3A** [comment] 2020-03-28 23:20
This is very similar to #211.
Which app version are you using? (latest is 0.5.10)

**Comment by penrods** [comment] 2020-03-28 23:52
I don't know if we can do much about this -- we simply record what the GPS signal shows us.  You said the group to the left is 160m away?  Are you often inside a large building or a place with dense walls?  I know the tracks around my house shows a cloud that covers about 4 houses worth of space, and then when I went to a grocery store it registered several points to the east of the store (very similar to your image).

**Comment by miquelvila** [comment] 2020-03-29 09:33
I was using version 0.5.6 when that happened.

Normally the same happens with my location trail, it covers about 4 houses around me. But being registered 106 times incorrectly by 120meters seems worrying

**Comment by E3V3A** [comment] 2020-03-29 14:14
@miquelvila 
Thanks for reporting,  but always make sure to update your app and try again. There's very active development here, so if you post issues with old apps, you are likely to just derail the development. 
If it doesn't happen again, please close the issue.

**Comment by miquelvila** [comment] 2020-03-29 15:24
@E3V3A I already checked before posting and it was happening anyway, but I lost the data when I updated the app

**Comment by penrods** [comment] 2020-03-29 22:50
I'm 95% certain the issue is with the actual phone GPS reporting.  We don't do anything special -- we just request position and save it.  If the point were 0,0 then I'd suspect a bug.  But 120m is too close to "right" -- this sounds like it isn't a software issue.

**Comment by E3V3A** [comment] 2020-03-30 18:40
For the 1st picture:  

I believe this may have something to do with Googles location services using a combination of WiFi, Mobile Cell Towers and GPS. So for example, if you're out of GPS coverage (which easily happens between/near buildings), it may rely on cell tower (BTS) location instead. And that location may be at the `Green "106"` point. Please have a look at that point an see if you can see a bunch of mobile antennas on/near that location.  Make sure you have a good GPS lock before you enable the app and try again. (Check with "GPS Status" app.)

For the 2nd:  

(I get the same thing, doing nothing at all, just turning on GPS and waiting.)

I believe it's a problem of how the positions are taken and stored. My guess is that the app just keep on storing new values, regardless of what's already been stored before. Obviously any 6-8 decimal GPS location will keep keep changing. This is why you need to throttle and check new positions and only add those that have moved a certain min distance within a certain min time. 

* For example:  `Moved  >5 meters` **AND** `last position was taken >20 seconds ago.`

**Comment by E3V3A** [comment] 2020-04-06 10:14
2nd picture now seem related to #360 and #363.

**Comment by diarmidmackenzie** [comment] 2020-04-11 21:39
I have seen similar issues with GPS signals leaping abut (rural Italy).

DHM-A1-16 in my test report here:
https://docs.google.com/document/d/1Uh1A-h7Ddm6t-rAlHOM90xnsrkLEG9SGcTolf3uIbgQ/edit

"I am indoors, in a rural location.  Phone has Wifi + SIM card with OK signal.
o   While stationary, over an hour, data varied as follows:
§  Lat: -0.0000012 to + 0.00015 (total variation: 0.00016)
§  Long: -0.0002873 to + 0.0007226 (total variation: 0.00101)
o   On the basis that 1 degree is approx. 100km, that’s ~100m variation."


I don't think it's enough to just say "it's the GPS signal / hardware" (@penrods above).  Almost certainly true, but if our software is making assumptions about GPS reliability, that are not in fact true, that remains a flaw in our software.

We need to analyze the risk, figure out what limitations it implies for the app, and determine whether there is anything we can do to workaround the problems.

In the worst case, unreliable GS signals are a fatal flaw that kills the entire app design.  Hopefully it's not that bad, but we should assess how bad it is, and what we might be able to do to mitigate.

First task is probably some research on reliability of GPS signals - there is probably existing literature available that will give us more insight that we can get from individual users testing.

**Comment by E3V3A** [comment] 2020-04-12 15:59
The `lat` and `lon` need to be [truncated to 5 decimals](https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude) (equivalent to ~1.1 meters) , otherwise you will get a lot crap out!

**Comment by penrods** [comment] 2020-04-18 09:52
No longer part of Safe Paths.

**Closed by penrods** 2020-04-18 09:52 UTC
Labels: Bug, For next release

**Comment by diarmidmackenzie** [comment] 2020-04-18 18:35
@penrods I don't understand - yes the UI is no longer part of the app, but GPS leaping about is still a potential issue, is it not?

Understand we can't do anything about the data we get back tom the GPS hardware, but we might need to look at mitigation in software for these bumps, or adjustment of matching algorithms to accommodate.
