### ISSUE TITLE
Discussion: Why contribute to a project that will not benefit anyone? 

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/covid-safe-paths#520] opened 2020-04-15 10:09 UTC
When I first found this project, it was while looking for useful contract tracing solutions. That was now nearly a month ago, and it sounded very sane and promising at that time. I was thinking that it would be great to help contributing to such a thing. However, since then, essentially nothing good has come out of this project, apart from a large number of other very talented people coming out of the woodwork, who also believe in the initial premises of the project. And *that* is the issue.

To make a long story short, I have decided to no longer contribute to this project as most of my concerns, and well founded suggestions are either mostly ignored or worse, addressing something with a dead-end since solid development mile-stones are non-existent (at best), or senseless at worst). 

I was recently sent this from user XXX, in a private slack message. 

> Hi E3v3a. I appreciate your focus on contact tracing. The core dev team is working very hard on pushing a V1.0 Minimum Viable Product. The 1.0/MVP SafePaths phone app will definitely support GPS logging (but not bluetooth proximity ID exchange, hardware issues with the variety of Bluetooth stacks). But that is only a small part of the full solution, the SafePlaces web app (which Heath Authorities use to import the GPS trace data from the SafePaths phone application is the primary focus. The full team is focusing on heath authorities (such as state/city health departments) as their primary client and working to roll out beta implementations. This middleware/app/website will work with our phone app, but also wants to support other contact tracing applications. Much of the work is business development, forming coalitions with stakeholders, etc.... and is not visible on github.

--- 

**This is my response to that:**  

Hi XXXX!

Thanks for reaching out, and thanks for trying to better explain the aim for the project. 
I now understand that this is a project I should not be working on. Why is that?

It's in my observation and current opinion that **this project is actually not serving the people on the street**, but rather the health authorities, while it has been sold, funded and marketed as exactly that, serving the people and doing it with privacy, infected or not. I cannot collaborate under these false pretenses, nor willing to contribute with my limited time (I am lucky to still have a day job) to a project I do not believe will help people stay at home, nor offering a way to be/feel safer. This is a disturbing lack of transparency, which is probably not intentional, but rather a direct result from the lack of clear management, communication, documentation and focus, for what seem to be an ever increasingly over-engineered project.

What people on the street want and need to know, is:

* Where are most infected people located in the last (1hr, 24hr, 1 week, 2 weeks) in my city/neighborhood?
* Where have I been in those time frames?
* What is my risk of having been infected (or infected someone else) at these locations?
* What were those locations? (important because the user may know a lot of other people who was with him/her and would like to inform them.)
* How can I share my own health status to this map?

Regarding the business development, you are doing an excellent job, but for the benefit of who exactly? 

A lot of the app issues that are being ignored or abandoned are doing so under the false pretense that it is by legal considerations. However, these considerations are mostly USA related and thus more or less totally irrelevant in the rest of the world. So are we working for a truly global project as NPO or another US backed business model tracking people, but without any direct and visible benefit to them? As already stated very well elsewhere: When your life is a risk, nobody gives a fuck about privacy or potential legal repercussions at a later time. This is the reality we are living right now. This is why I am not interested in supporting something that will take several months to complete and will not have any use, nor make a difference in the continued increasing spread in a large part of the world. (Yes, I also hope to be wrong here, but I have been following the C19 progression modeling and research since, mid January, and so far, no "technology" has been able to help reducing this, apart using face-masks and disinfectants.)

Now you claim it is a BT "hardware" problem, preventing to use BT as close proximity detection.  No it is not. It is a pure software problem where devs are simply too lazy to have to write a little extra code to navigate around old and new BT stacks, and their different implementations and blah blah. BTW. BT stacks are generally all based on the same code base. In addition, it also seem to be more of an iPhone problem than Android. So why not call up Apple and ask for a workaround? They are supposedly already "supporting" this project and proposing a new API, so let's see if they can deliver on those promises.

**Not having BT for proximity**, is going to be very bad in densely populated urban areas, where building radio shadows often give very sketchy results, unless you're outside in the middle of the street, which is already an unlikely place to be infected. At least in places like NYC. **It will also render the app useless while being inside or under ground**, which is now the most probable place to be infected. For example, in super-markets, subways, buses and trams, offices and inside elder-homes.

Then there are other far more urgent issues, but which still have not been addressed and mostly ignored, even though repeatedly appearing again and again in issues, in discussions and in Slack threads etc.

The more pressing issues are:

* Most people in the world have limited data plans with pre-paid mobile plans. How are they supposed to download their 500 MB 2 week location data without risking to get their data services cut out? 
* Most people in the world do not have high speed LTE (4G+) coverage from their MNO's. How are they going to successfully download/upload any large quantities of data required for this app, in reasonable time?
* Many people in the world are still not using Google's email and Play Store. (Usually because of Gov't blockage.) How are they supposed to get access to location data?
* Many other people use different emails for their work phones which are not connected to Play Store via Gmail, as imposed by using sensible privacy policies at many companies. (I.e. when the phone is provided by company.) How can they access and use this app?
* Most people in the world are not using the latest iPhone or Android 9 (~40% using AOS 8.) How can they contribute with their data?

I would love to see some official clarity  on how and when this project intend to address these very fundamental issues.

**Comment by summetj** [comment] 2020-04-15 12:46
Thank you for considering using your talents to assist this project.
We have determined that (at least within the US, which is our first target for beta rollouts) the local health departments are a key client and enabler of solutions. (Technology can not solve all problems on it's own, and we are focusing on assisting the local health authorities do the full contact tracing procedure.)  Privacy for the "person on the street" is still very much a guiding principle, but we feel the best way to help all individuals is to empower a community response guided by the pre-existing local health authorities.  

 I will keep your comments in mind as we proceed forward and do my best to assist the project in ways that help the most people.

**Comment by E3V3A** [comment] 2020-04-15 13:25
@summetj 
Thanks for trying to explain.

>  ... we feel the best way to help all individuals is to empower a community response guided by the pre-existing local health authorities.

They are a little busy these times, and in most contries they don't have the extra manpower nor technical knowledge to support a brand new (and relatively poorly documented)  IT project, that involve obtaining, configuring and maintaining, any amount of technological infrastructure.

> will not be available for our very first release

Your *very first release* was on the 6th of March, which is 19 useless releases ago... 

* Why are you even putting this app on the Play Store, when all you are doing is inciting false hope of people thinking they are actually contributing to something, when in fact the app does **nothing**! Almost every C-19 related app has been pulled from the PS, and many of them even worked to some extent, but for some unknown reason, this dysfunctional app is still there.

**Comment by DavidSReich** [comment] 2020-04-16 05:19
I'm new to this project ... so not trying to "defend" it yet.
I recently joined the Xerobase project, too.  It's an app-less solution.
Since I'm a native iOS dev there's not much I can do on either project right now.
I worked on the Auspost DigitalID app when it was at the very beginning.  It had similar issues of functioning in a vacuum at the beginning.

Apps are "easy" and just the tip of the iceberg.
For any system like this (contact tracing) to be effective the back-end/cloud/server/web sides need to be implemented first, and have wide buy-in from governmental and health-care stakeholders.  And there are all sorts of privacy regulations and health data regulations across multiple jurisdictions.

There are ~195 countries today.  (And 50 states in the U.S.  And who knows how many independent states/provinces/etc in other countries!)
Getting buy-in from all of them will be difficult unless some large non-political international entity is involved.  I don't have a solution to that problem, but I do know that just throwing apps at the problem isn't a long-term solution.

I too am frustrated about not being able to find any useful app development projects I can contribute to.  (Otherwise I would be working on that instead of commenting here!)  There are dozens (more?) of app projects for contact tracing.  None of them will be useful without an IT ecosystem to connect to.

**Comment by penrods** [comment] 2020-04-18 09:36
I appreciate your interest in this project and the input you have provided.  If this does not seem to be aligned with your personal beliefs and goals, I wish you the best of luck.  But please do not post inflammatory issues such as this which have nothing which can not be addressed by the software.  I am also frustrated by the global situation and the speed at which governments move, but it is what it is and (in my opinon) we have to work with the system -- this is a time for cooperation, not revolution.

**Closed by penrods** 2020-04-18 09:36 UTC
